language: bash
dist: xenial

before_install:
- sudo chmod u+x .travis/*.sh
- /bin/bash .travis/setup.sh

script:
# build 
- sudo singularity build Singularity.simg Singularity
# test
- /bin/bash .travis/test.sh
